# Generated by Django 3.2.16 on 2022-10-09 02:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0003_alter_student_options'),
        ('discipline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_user', models.UUIDField()),
                ('update_user', models.UUIDField(null=True)),
                ('grade', models.PositiveIntegerField(verbose_name='Nota do aluno')),
                ('delivery_date', models.DateTimeField(verbose_name='Data e hora de entrega do boletim')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discipline.discipline')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.student')),
            ],
            options={
                'verbose_name': 'Boletim',
            },
        ),
    ]
