# Generated by Django 3.2.16 on 2022-10-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='delivery_date',
            field=models.DateField(verbose_name='Data de entrega do boletim'),
        ),
    ]
