# Generated by Django 3.2.16 on 2022-10-08 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Aluno'},
        ),
    ]
